<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Masjid Jami Cicangkudu</title>
    <link rel="stylesheet" href="{{ asset('bootstrap/css/bootstrap.min.css') }}"><link rel="stylesheet" href="{{ asset('fontawesome/css/all.min.css') }}">
    <style>body{font-family:system-ui,-apple-system,sans-serif;background:#f8faf8;color:#17251b}.hero{background:linear-gradient(135deg,#0b5c3d,#17764f);color:#fff}.brand{font-family:Georgia,serif;font-weight:700}.section{padding:5rem 0}.card{border:0;border-radius:1rem;box-shadow:0 .3rem 1rem #1233}.icon{width:48px;height:48px;border-radius:50%;display:grid;place-items:center;background:#e8f5e9;color:#0b5c3d}.program{border-left:4px solid #198754}.muted{color:#d9f0e2}.image{height:170px;width:100%;object-fit:cover;border-radius:1rem 1rem 0 0}.hero-image{width:100%;height:260px;object-fit:cover;border-radius:1rem}</style>
</head>
<body>
<nav class="navbar bg-white sticky-top shadow-sm"><div class="container py-2"><a class="navbar-brand brand text-success" href="#beranda"><i class="fa-solid fa-mosque me-2"></i>Masjid Jami Cicangkudu</a><div class="d-flex gap-2"><a class="btn btn-outline-success" href="#informasi">Informasi</a><a class="btn btn-success" href="{{ route('login') }}">Masuk Warga</a></div></div></nav>
<section id="beranda" class="hero"><div class="container section"><div class="row align-items-center g-5"><div class="col-lg-7"><span class="badge text-bg-light text-success mb-3">Sistem Digital Masjid</span><h1 class="display-4 brand">{{ $profile?->name ?? 'Masjid Jami Cicangkudu' }}</h1><p class="lead muted">{{ $profile?->description ?? 'Informasi masjid, berita kegiatan, dan program donasi dalam satu tempat.' }}</p><div class="d-flex gap-2 flex-wrap"><a href="#donasi" class="btn btn-light btn-lg text-success">Lihat Donasi</a><a href="#informasi" class="btn btn-outline-light btn-lg">Berita Masjid</a></div></div><div class="col-lg-5">@if($profile?->image_path)<img class="hero-image shadow" src="{{ asset('storage/'.$profile->image_path) }}" alt="Foto {{ $profile->name }}">@else<div class="bg-white text-dark rounded-4 p-4 shadow"><div class="icon mb-3"><i class="fa-solid fa-moon"></i></div><strong>Untuk warga</strong><p class="text-muted mb-0 mt-2">Masuk untuk membayar kas keluarga, melihat jadwal salat, dan mengakses laporan.</p></div>@endif</div></div></div></section>
<section class="section py-5"><div class="container"><div class="d-flex justify-content-between align-items-center mb-3"><div><h2 class="brand mb-1">Jadwal Salat Hari Ini</h2><p class="text-muted mb-0">Cicangkudu, Mangunreja, Kabupaten Tasikmalaya</p></div><span class="badge text-bg-success">WIB</span></div><div class="row g-3">@forelse($prayers as $prayer)<div class="col-6 col-md"><div class="card text-center p-3"><small class="text-muted">{{ $prayer['name'] }}</small><strong class="fs-4 text-success">{{ $prayer['time'] }}</strong></div></div>@empty<div class="text-muted">Jadwal salat belum tersedia.</div>@endforelse</div></div></section>
<section id="informasi" class="section"><div class="container"><h2 class="brand">Informasi & Berita Terbaru</h2><p class="text-muted mb-4">Kabar dan kegiatan dari Masjid Jami Cicangkudu.</p><div class="row g-4">@forelse($news as $item)<div class="col-md-4"><article class="card h-100 overflow-hidden">@if($item->image_path)<img class="image" src="{{ asset('storage/'.$item->image_path) }}" alt="{{ $item->title }}">@endif<div class="card-body"><small class="text-success fw-semibold">{{ $item->event_date?->locale('id')->translatedFormat('d F Y') ?? 'Informasi Masjid' }}</small><h5 class="mt-2">{{ $item->title }}</h5><p class="text-muted mb-0">{{ \Illuminate\Support\Str::limit($item->description, 120) }}</p></div></article></div>@empty<div class="col-12"><div class="alert alert-light border">Informasi masjid akan segera ditampilkan di sini.</div></div>@endforelse</div></div></section>
<section id="donasi" class="section bg-white"><div class="container"><h2 class="brand">Program Donasi</h2><p class="text-muted mb-4">Dukung program kebaikan Masjid Jami Cicangkudu.</p><div class="row g-4">@forelse($programs as $program)<div class="col-md-4"><div class="card h-100 program"><div class="card-body"><div class="icon mb-3"><i class="fa-solid fa-hand-holding-heart"></i></div><h5>{{ $program->title }}</h5><p class="text-muted">{{ \Illuminate\Support\Str::limit($program->description, 110) }}</p>@if($program->amount)<strong class="text-success">Target Rp {{ number_format($program->amount,0,',','.') }}</strong>@endif</div></div></div>@empty<div class="col-12"><div class="alert alert-light border">Program donasi akan segera tersedia.</div></div>@endforelse</div><a href="{{ route('login') }}" class="btn btn-success mt-4">Masuk untuk Berdonasi</a></div></section>
<footer class="bg-dark text-white py-4"><div class="container d-flex justify-content-between flex-wrap gap-2"><span>© {{ date('Y') }} Masjid Jami Cicangkudu</span><a class="text-white" href="{{ route('admin.login') }}">Masuk Admin</a></div></footer>
</body></html>
