@extends('admin.layout')
@section('title', isset($kasKk) ? 'Edit Kas KK' : 'Catat Kas KK')
@section('header', 'Kelola Kas KK')
@section('content')
<div class="mb-4"><a class="text-decoration-none text-muted small" href="{{ route('admin.kas-kk.index',['bulan'=>$bulan,'tahun'=>$tahun]) }}"><i class="fa-solid fa-arrow-left me-1"></i>Kembali ke Kas KK</a><h2 class="fw-bold mt-2" style="font-family:serif">{{ isset($kasKk) ? 'Edit' : 'Catat' }} Pembayaran Kas KK</h2><p class="text-muted">Catatan manual admin langsung berstatus terverifikasi. Pembayaran warga diproses melalui unggah bukti.</p></div>
@if($families->isEmpty())<div class="alert alert-warning">Belum ada data KK. <a href="{{ route('admin.families.create') }}">Tambah KK terlebih dahulu.</a></div>@else<div class="card border-0 shadow-sm" style="border-radius:1rem"><div class="card-body p-4"><form method="POST" action="{{ isset($kasKk) ? route('admin.kas-kk.update',$kasKk) : route('admin.kas-kk.store') }}">@csrf @isset($kasKk) @method('PUT') @endisset<input type="hidden" name="status" value="verified"><div class="row g-3"><div class="col-md-6"><label class="form-label">No. KK</label><select id="familyId" name="family_id" class="form-select @error('family_id') is-invalid @enderror" required><option value="">Pilih KK</option>@foreach($families as $family)<option value="{{ $family->id }}" data-golongan="{{ $family->golongan }}" data-nominal="{{ $family->nominal_kas }}" @selected((string)old('family_id',$kasKk->family_id ?? request('family_id'))===(string)$family->id)>{{ $family->no_kk }} · Golongan {{ $family->golongan }}</option>@endforeach</select>@error('family_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-md-3"><label class="form-label">Golongan</label><input id="golonganInfo" class="form-control bg-light" readonly></div><div class="col-md-3"><label class="form-label">Nominal</label><input id="nominalInfo" class="form-control bg-light" readonly></div><div class="col-md-6"><label class="form-label">Pembayar</label><select id="payer" name="user_id" class="form-select @error('user_id') is-invalid @enderror" required><option value="">Pilih anggota KK</option>@foreach($warga as $user)<option value="{{ $user->id }}" data-family="{{ $user->wargaProfile?->family_id }}" @selected((string)old('user_id',$kasKk->user_id ?? '')===(string)$user->id)>{{ $user->name }} · NIK {{ $user->wargaProfile?->nik ?? '-' }} · {{ $user->wargaProfile?->family?->no_kk ?? 'Tanpa KK' }}</option>@endforeach</select>@error('user_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-md-3"><label class="form-label">Bulan</label><select name="bulan" class="form-select">@for($i=1;$i<=12;$i++)<option value="{{ $i }}" @selected((int)old('bulan',$bulan)===$i)>{{ \Carbon\Carbon::create(null,$i,1)->translatedFormat('F') }}</option>@endfor</select></div><div class="col-md-3"><label class="form-label">Tahun</label><input name="tahun" type="number" min="2020" max="2100" class="form-control" value="{{ old('tahun',$tahun) }}"></div><div class="col-md-4"><label class="form-label">Tanggal pembayaran</label><input id="tanggal" name="tanggal_pembayaran" type="date" class="form-control" value="{{ old('tanggal_pembayaran',isset($kasKk) && $kasKk->tanggal_pembayaran ? $kasKk->tanggal_pembayaran->format('Y-m-d') : now()->toDateString()) }}" required></div></div><button class="btn btn-success mt-4">Simpan Catatan Kas</button></form></div></div>@endif
@endsection
@push('scripts')<script>
const family=document.getElementById('familyId'), payer=document.getElementById('payer');
function refreshFamily(){const option=family.options[family.selectedIndex];document.getElementById('golonganInfo').value=option.dataset.golongan ? 'Golongan '+option.dataset.golongan : '';document.getElementById('nominalInfo').value=option.dataset.nominal ? new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(option.dataset.nominal) : '';[...payer.options].forEach(option=>{if(!option.value)return;option.hidden=option.dataset.family!==family.value;});if(payer.selectedOptions[0]?.hidden)payer.value='';}
family?.addEventListener('change',refreshFamily);refreshFamily();
</script>@endpush
