@extends('admin.layout')
@section('title', 'Kelola Kas KK | Admin Masjid')
@section('header', 'Kelola Kas KK')
@section('content')
@php($labels=['pending'=>['Menunggu Verifikasi','warning'],'verified'=>['Sudah Bayar','success'],'rejected'=>['Ditolak','danger'],'belum_bayar'=>['Belum Bayar','secondary']])
<div class="d-flex flex-column flex-md-row justify-content-between align-items-md-end gap-3 mb-4"><div><h2 class="fw-bold mb-1" style="font-family:serif">Kas berdasarkan Kartu Keluarga</h2><p class="text-muted mb-0">Bukti pembayaran warga harus diverifikasi sebelum masuk sebagai pemasukan.</p></div><a href="{{ route('admin.kas-kk.create',['bulan'=>$bulan,'tahun'=>$tahun]) }}" class="btn btn-success"><i class="fa-solid fa-plus me-1"></i>Catat Manual</a></div>
<div class="card border-0 shadow-sm mb-4" style="border-radius:1rem"><div class="card-body p-3"><form method="GET" class="row g-2 align-items-end"><div class="col-md-3"><label class="form-label small">Bulan</label><select name="bulan" class="form-select">@for($i=1;$i<=12;$i++)<option value="{{ $i }}" @selected($bulan===$i)>{{ \Carbon\Carbon::create(null,$i,1)->translatedFormat('F') }}</option>@endfor</select></div><div class="col-md-2"><label class="form-label small">Tahun</label><input name="tahun" type="number" class="form-control" value="{{ $tahun }}"></div><div class="col-md-3"><label class="form-label small">Status</label><select name="status" class="form-select"><option value="">Semua status</option>@foreach($labels as $value=>$label)<option value="{{ $value }}" @selected($status===$value)>{{ $label[0] }}</option>@endforeach</select></div><div class="col-md-2"><button class="btn btn-outline-success w-100"><i class="fa-solid fa-filter me-1"></i>Filter</button></div></form></div></div>
<div class="row g-3 mb-4"><div class="col-md-3"><div class="card border-0 shadow-sm"><div class="card-body"><small class="text-muted">KK terdaftar</small><strong class="d-block fs-4">{{ $semuaKk }} / 100 KK</strong></div></div></div><div class="col-md-3"><div class="card border-0 shadow-sm"><div class="card-body"><small class="text-muted">Terverifikasi</small><strong class="d-block fs-4 text-success">{{ $sudahBayar }} KK</strong></div></div></div><div class="col-md-3"><div class="card border-0 shadow-sm"><div class="card-body"><small class="text-muted">Belum lunas</small><strong class="d-block fs-4 text-danger">{{ max(0,$semuaKk-$sudahBayar) }} KK</strong></div></div></div><div class="col-md-3"><div class="card border-0 shadow-sm"><div class="card-body"><small class="text-muted">Pemasukan terverifikasi</small><strong class="d-block fs-5 text-success">Rp {{ number_format($totalPemasukan,0,',','.') }}</strong></div></div></div></div>
<div class="card border-0 shadow-sm" style="border-radius:1rem"><div class="card-body p-4"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead class="table-light"><tr><th>No.</th><th>No. KK</th><th>Golongan</th><th>Kas</th><th>Nama pembayar / NIK</th><th>Bukti</th><th>Status</th><th class="text-center">Aksi</th></tr></thead><tbody>@forelse($families as $family)@php($payment=$family->paymentPeriode)@php($paymentStatus=$payment?->status ?? 'belum_bayar')<tr><td class="text-muted">{{ $loop->iteration }}</td><td class="fw-semibold">{{ $family->no_kk }}</td><td>Golongan {{ $family->golongan }}</td><td>Rp {{ number_format($family->nominal_kas,0,',','.') }}</td><td>@if($payment?->payer)<span class="fw-semibold">{{ $payment->payer->name }}</span><small class="d-block text-muted">NIK: {{ $payment->payer->wargaProfile?->nik ?? '-' }}</small>@else<span class="text-muted">Belum ada pembayaran</span>@endif</td><td>@if($payment?->proof_path)<a class="btn btn-sm btn-outline-primary" target="_blank" href="{{ asset('storage/'.$payment->proof_path) }}">Lihat</a>@else-@endif</td><td><span class="badge bg-{{ $labels[$paymentStatus][1] }}">{{ $labels[$paymentStatus][0] }}</span></td><td><div class="d-flex gap-1 justify-content-center">@if($payment)<a class="btn btn-sm btn-outline-info" href="{{ route('admin.kas-kk.show',$payment) }}" title="Detail"><i class="fa-solid fa-eye"></i></a>@if($payment->status==='pending')<form method="POST" action="{{ route('admin.kas-kk.verify',$payment) }}">@csrf @method('PUT')<button class="btn btn-sm btn-success" title="Verifikasi" onclick="return confirm('Verifikasi pembayaran kas ini?');"><i class="fa-solid fa-check"></i></button></form><form method="POST" action="{{ route('admin.kas-kk.reject',$payment) }}">@csrf @method('PUT')<button class="btn btn-sm btn-outline-danger" title="Tolak" onclick="return confirm('Tolak bukti pembayaran ini?');"><i class="fa-solid fa-xmark"></i></button></form>@else<a class="btn btn-sm btn-outline-primary" href="{{ route('admin.kas-kk.edit',$payment) }}" title="Edit"><i class="fa-solid fa-pen"></i></a>@endif<form method="POST" action="{{ route('admin.kas-kk.destroy',$payment) }}" onsubmit="return confirm('Hapus catatan kas ini?');">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger" title="Hapus"><i class="fa-solid fa-trash"></i></button></form>@else<a class="btn btn-sm btn-success" href="{{ route('admin.kas-kk.create',['bulan'=>$bulan,'tahun'=>$tahun,'family_id'=>$family->id]) }}">Catat</a>@endif</div></td></tr>@empty<tr><td colspan="8" class="text-center text-muted py-4">Belum ada KK terdaftar.</td></tr>@endforelse</tbody></table></div></div></div>
@endsection
