@extends('warga.layout')
@section('title', 'Dashboard Warga | Masjid Jami Cicangkudu')
@section('header', 'Dashboard warga')
@section('content')
<div class="hero-grid"><section class="welcome-hero"><div class="hero-kicker">Cicangkudu · Mangunreja · Tasikmalaya</div><h1>Assalamu'alaikum, {{ auth()->user()->name ?? 'Warga' }}.</h1><p>Jadwal salat, informasi masjid, donasi, dan laporan keuangan dalam satu tempat.</p></section><section class="next-prayer"><span class="muted-label">Salat berikutnya</span>@if($nextPrayer)<strong class="next-time">{{ $nextPrayer['time'] }}</strong><strong class="next-name">{{ $nextPrayer['name'] }}</strong><span class="next-meta">{{ $nextPrayer['at']->diffForHumans(now('Asia/Jakarta'), true) }} lagi</span>@else<strong class="next-name mt-3">Jadwal belum tersedia</strong><span class="next-meta mt-2">Coba muat ulang beberapa saat lagi.</span>@endif<div class="prayer-progress"><i></i></div><div class="progress-meta"><span>Kabupaten Tasikmalaya</span><span>WIB</span></div></section></div>
<div class="section-heading"><h2>Menu cepat</h2><a href="{{ route('informasi') }}">Informasi masjid</a></div><div class="quick-grid"><a href="{{ route('jadwal') }}" class="quick-link"><i class="fa-solid fa-clock"></i><strong>Jadwal salat</strong><small>Hari ini</small></a><a href="{{ route('informasi') }}" class="quick-link"><i class="fa-solid fa-mosque"></i><strong>Informasi</strong><small>Berita & kegiatan</small></a><a href="{{ route('donasi') }}" class="quick-link"><i class="fa-solid fa-heart"></i><strong>Donasi</strong><small>Program berjalan</small></a><a href="{{ route('kas.saya') }}" class="quick-link"><i class="fa-solid fa-wallet"></i><strong>Kas Keluarga</strong><small>Status kas KK</small></a><a href="{{ route('laporan') }}" class="quick-link"><i class="fa-solid fa-chart-column"></i><strong>Laporan</strong><small>Transparansi DKM</small></a></div>
<div class="section-heading"><h2>Progres donasi</h2><a href="{{ route('donasi') }}">Lihat program</a></div><div class="content-card donation-progress-list">@forelse($donationProgress as $program)<div class="donation-progress-row"><div class="donation-progress-head"><div><strong>{{ $program->title }}</strong><span>Rp {{ number_format($program->collected_amount, 0, ',', '.') }} dari Rp {{ number_format((float) $program->amount, 0, ',', '.') }}</span></div><b>{{ $program->progress_percent }}%</b></div><div class="donation-progress-bar"><i style="width: {{ $program->progress_percent }}%"></i></div></div>@empty<div class="text-muted text-center py-3">Belum ada program donasi aktif.</div>@endforelse</div>
<div class="section-heading"><h2>Progres Kas KK</h2><a href="{{ route('kas.saya') }}">Lihat kas keluarga</a></div><div class="content-card donation-progress-list"><div class="donation-progress-row"><div class="donation-progress-head"><div><strong>Kas {{ now('Asia/Jakarta')->translatedFormat('F Y') }}</strong><span>{{ $kasTerverifikasi }} dari {{ $totalKk }} KK sudah terverifikasi · Rp {{ number_format($pemasukanKas, 0, ',', '.') }}</span></div><b>{{ $kasProgressPercent }}%</b></div><div class="donation-progress-bar"><i style="width: {{ $kasProgressPercent }}%"></i></div></div></div>
<div class="dashboard-columns"><section><div class="section-heading"><h2>Jadwal salat hari ini</h2><a href="{{ route('jadwal') }}">Buka jadwal</a></div><div class="content-card prayer-list">@forelse($prayers as $prayer)<div class="prayer-line {{ $nextPrayer && $nextPrayer['name'] === $prayer['name'] ? 'current' : '' }}"><strong>{{ $prayer['name'] }}</strong><b>{{ $prayer['time'] }}</b><span>{{ $nextPrayer && $nextPrayer['name'] === $prayer['name'] ? 'Berikutnya' : ($prayer['at']->isPast() ? 'Selesai' : 'Akan datang') }}</span></div>@empty<div class="text-muted text-center py-3">Jadwal belum dapat dimuat.</div>@endforelse</div></section><section><div class="section-heading"><h2>Informasi terbaru</h2><a href="{{ route('informasi') }}">Semua</a></div><div class="content-card event-list">@forelse($information as $item)<div class="event-row"><time><b>{{ $item->event_date?->format('d') ?? $item->created_at->format('d') }}</b><small>{{ strtoupper($item->event_date?->translatedFormat('M') ?? $item->created_at->translatedFormat('M')) }}</small></time><div><strong>{{ $item->title }}</strong><span>{{ \Illuminate\Support\Str::limit($item->description, 56) }}</span></div></div>@empty<div class="text-muted text-center py-3">Belum ada informasi yang diterbitkan.</div>@endforelse</div></section></div>
@endsection
