@extends('warga.layout')
@section('title', 'Donasi | Masjid Jami Cicangkudu')
@section('header', 'Donasi')
@section('content')
<div class="mb-4"><a href="{{ route('dashboard') }}" class="text-decoration-none text-muted small"><i class="fa-solid fa-arrow-left me-1"></i>Kembali ke Dashboard</a><h2 class="fw-bold mt-2" style="font-family:serif">Donasi Masjid</h2><p class="text-muted">Salurkan donasi lalu unggah bukti transfer untuk diverifikasi pengurus.</p></div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
<div class="row g-4 mb-4">
    <div class="col-lg-7"><div class="card border-0 shadow-sm h-100" style="border-radius:1rem"><div class="card-body p-4"><h5 class="fw-bold">Program Donasi</h5><div class="row g-3">@forelse($programs as $program)<div class="col-md-6"><div class="border rounded-3 p-3 h-100">@if($program->image_path)<img src="{{ asset('storage/'.$program->image_path) }}" class="w-100 rounded mb-2" style="height:120px;object-fit:cover" alt="">@endif<h6 class="fw-bold">{{ $program->title }}</h6><p class="small text-muted mb-0">{{ \Illuminate\Support\Str::limit($program->description, 100) }}</p></div></div>@empty<div class="col-12 text-muted small">Belum ada program aktif. Donasi tetap dapat dikirim sebagai donasi umum.</div>@endforelse</div></div></div></div>
    <div class="col-lg-5"><div class="card border-0 shadow-sm h-100" style="border-radius:1rem"><div class="card-body p-4"><h5 class="fw-bold">Pembayaran</h5><div class="bg-light rounded-3 p-3 mb-3 text-center">@if($paymentSetting?->qris_path)<img src="{{ asset('storage/'.$paymentSetting->qris_path) }}" class="img-fluid" style="max-height:180px" alt="QRIS Masjid">@else<i class="fa-solid fa-qrcode fs-1 text-success"></i><strong class="d-block mt-2">QRIS belum diatur</strong>@endif</div><div class="border rounded-3 p-3"><small class="text-muted">{{ $paymentSetting?->bank_name ?? 'Rekening belum diatur' }}</small><strong class="d-block fs-5 font-monospace">{{ $paymentSetting?->account_number ?? '-' }}</strong><span class="small">a.n. {{ $paymentSetting?->account_name ?? 'DKM Masjid Jami Cicangkudu' }}</span></div></div></div></div>
</div>
<div class="card border-0 shadow-sm" style="border-radius:1rem"><div class="card-body p-4"><h5 class="fw-bold mb-3">Konfirmasi Donasi</h5><form method="POST" action="{{ route('donasi.store') }}" enctype="multipart/form-data">@csrf<div class="row g-3"><div class="col-md-6"><label class="form-label">Program</label><select name="masjid_content_id" class="form-select"><option value="">Donasi umum</option>@foreach($programs as $program)<option value="{{ $program->id }}">{{ $program->title }}</option>@endforeach</select></div><div class="col-md-6"><label class="form-label">Nominal (Rp)</label><input type="number" min="1000" name="amount" class="form-control @error('amount') is-invalid @enderror" required value="{{ old('amount') }}">@error('amount')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-md-6"><label class="form-label">Metode pembayaran</label><select id="metodeDonasi" name="payment_method" class="form-select"><option value="qris">QRIS</option><option value="transfer_bank">Transfer bank</option><option value="cash">Tunai / cash ke pengurus</option></select><small class="text-muted">Donasi tunai akan dikonfirmasi pengurus.</small></div><div id="buktiDonasi" class="col-md-6"><label class="form-label">Bukti transfer (JPG, PNG, atau PDF)</label><input id="proofDonasi" type="file" name="proof" class="form-control @error('proof') is-invalid @enderror" required accept="image/jpeg,image/png,application/pdf">@error('proof')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div><button class="btn btn-success mt-4 px-4"><i class="fa-solid fa-paper-plane me-1"></i>Kirim Donasi</button></form></div></div>
@push('scripts')<script>const metodeDonasi=document.getElementById('metodeDonasi'),buktiDonasi=document.getElementById('buktiDonasi'),proofDonasi=document.getElementById('proofDonasi');function aturBuktiDonasi(){const tunai=metodeDonasi.value==='cash';buktiDonasi.classList.toggle('d-none',tunai);proofDonasi.required=!tunai}metodeDonasi?.addEventListener('change',aturBuktiDonasi);aturBuktiDonasi();</script>@endpush
@endsection
