@extends('warga.layout')
@section('title', 'Informasi Masjid | Masjid Jami Cicangkudu')
@section('header', 'Informasi Masjid')
@section('content')
<div class="mb-4"><a href="{{ route('dashboard') }}" class="text-decoration-none text-muted small"><i class="fa-solid fa-arrow-left me-1"></i> Kembali ke Dashboard</a><h2 class="fw-bold mt-2" style="font-family:serif">Masjid Jami Cicangkudu</h2><p class="text-muted">Profil, layanan, dan berita terbaru masjid.</p></div>
<div class="card border-0 shadow-sm mb-4 overflow-hidden" style="border-radius:1rem"><div class="row g-0"><div class="col-md-5"><img src="{{ asset('images/images.jpg') }}" class="w-100 h-100" style="object-fit:cover;min-height:260px" alt="Kegiatan Masjid Jami Cicangkudu"></div><div class="col-md-7"><div class="card-body p-4"><span class="badge bg-success bg-opacity-10 text-success mb-2">Profil Masjid</span><h3 class="fw-bold">Masjid Jami Cicangkudu</h3><p class="text-muted">Pusat ibadah, pendidikan Al-Qur'an, serta kegiatan sosial warga Cicangkudu.</p><hr><div class="row small g-3"><div class="col-sm-6"><i class="fa-solid fa-location-dot text-success me-2"></i>Cicangkudu, Mangunreja, Kab. Tasikmalaya</div><div class="col-sm-6"><i class="fa-solid fa-mosque text-success me-2"></i>Masjid Jami</div><div class="col-sm-6"><i class="fa-solid fa-clock text-success me-2"></i>Terbuka setiap hari</div><div class="col-sm-6"><i class="fa-solid fa-users text-success me-2"></i>Pusat kegiatan warga</div></div></div></div></div></div>
<div class="row g-4 mb-4"><div class="col-md-6"><div class="card border-0 shadow-sm h-100" style="border-radius:1rem"><div class="card-body p-4"><h5 class="fw-bold"><i class="fa-solid fa-eye text-success me-2"></i>Visi</h5><p class="text-muted mb-0">Mewujudkan masjid sebagai pusat ibadah, pendidikan, dan kegiatan sosial yang bermanfaat bagi masyarakat.</p></div></div></div><div class="col-md-6"><div class="card border-0 shadow-sm h-100" style="border-radius:1rem"><div class="card-body p-4"><h5 class="fw-bold"><i class="fa-solid fa-bullseye text-success me-2"></i>Misi</h5><p class="text-muted mb-0">Melayani jamaah dengan terbuka, menguatkan kegiatan keagamaan, dan menjaga transparansi program masjid.</p></div></div></div></div>
<div class="d-flex justify-content-between align-items-center mb-3"><h4 class="fw-bold mb-0" style="font-family:serif">Berita & Pengumuman</h4><span class="text-muted small">Dikelola oleh admin</span></div><div class="row g-4">@forelse($news as $item)<div class="col-md-6 col-lg-4"><article class="card border-0 shadow-sm h-100 overflow-hidden" style="border-radius:1rem">@if($item->image_path)<img src="{{ asset('storage/'.$item->image_path) }}" style="height:180px;object-fit:cover" alt="{{ $item->title }}">@endif<div class="card-body p-4"><small class="text-success">{{ $item->event_date?->translatedFormat('d F Y') ?? 'Pengumuman' }}</small><h5 class="fw-bold mt-1">{{ $item->title }}</h5><p class="text-muted small mb-0">{{ $item->description }}</p></div></article></div>@empty<div class="col-12"><div class="card border-0 bg-light"><div class="card-body text-muted">Belum ada berita yang diterbitkan. Admin dapat menambahkannya dari menu Kelola Informasi Masjid.</div></div></div>@endforelse</div>
@endsection
