@extends('warga.layout')
@section('title', 'Informasi Masjid | Masjid Jami Cicangkudu')
@section('header', 'Informasi Masjid')
@section('content')
@php
    $namaMasjid = $profile?->name ?? 'Masjid Jami Cicangkudu';
    $deskripsi = $profile?->description ?? "Pusat ibadah, pendidikan Al-Qur'an, serta kegiatan sosial warga Cicangkudu.";
    $alamat = $profile?->address ?? 'Cicangkudu, Mangunreja, Kab. Tasikmalaya';
    $jenisMasjid = $profile?->masjid_type ?? 'Masjid Jami';
    $jamBuka = $profile?->open_hours ?? 'Terbuka setiap hari';
    $labelKegiatan = $profile?->activity_label ?? 'Pusat kegiatan warga';
    $visi = $profile?->vision ?? 'Mewujudkan masjid sebagai pusat ibadah, pendidikan, dan kegiatan sosial yang bermanfaat bagi masyarakat.';
    $misi = $profile?->mission ?? 'Melayani jamaah dengan terbuka, menguatkan kegiatan keagamaan, dan menjaga transparansi program masjid.';
@endphp
<div class="mb-4"><a href="{{ route('dashboard') }}" class="text-decoration-none text-muted small"><i class="fa-solid fa-arrow-left me-1"></i> Kembali ke Dashboard</a><h2 class="fw-bold mt-2" style="font-family:serif">{{ $namaMasjid }}</h2><p class="text-muted">Profil, layanan, informasi, dan kegiatan terbaru masjid.</p></div>
<div class="card border-0 shadow-sm mb-4 overflow-hidden" style="border-radius:1rem"><div class="row g-0"><div class="col-md-5">@if($profile?->image_path)<img src="{{ asset('storage/'.$profile->image_path) }}" class="w-100 h-100" style="object-fit:cover;min-height:260px" alt="{{ $namaMasjid }}">@else<img src="{{ asset('images/images.jpg') }}" class="w-100 h-100" style="object-fit:cover;min-height:260px" alt="{{ $namaMasjid }}">@endif</div><div class="col-md-7"><div class="card-body p-4"><span class="badge bg-success mb-2">Profil Masjid</span><h3 class="fw-bold">{{ $namaMasjid }}</h3><p class="text-muted">{{ $deskripsi }}</p><hr><div class="row small g-3"><div class="col-sm-6"><i class="fa-solid fa-location-dot text-success me-2"></i>{{ $alamat }}</div><div class="col-sm-6"><i class="fa-solid fa-mosque text-success me-2"></i>{{ $jenisMasjid }}</div><div class="col-sm-6"><i class="fa-solid fa-clock text-success me-2"></i>{{ $jamBuka }}</div><div class="col-sm-6"><i class="fa-solid fa-users text-success me-2"></i>{{ $labelKegiatan }}</div></div></div></div></div></div>
<div class="row g-4 mb-4"><div class="col-md-6"><div class="card border-0 shadow-sm h-100" style="border-radius:1rem"><div class="card-body p-4"><h5 class="fw-bold"><i class="fa-solid fa-eye text-success me-2"></i>Visi</h5><p class="text-muted mb-0">{{ $visi }}</p></div></div></div><div class="col-md-6"><div class="card border-0 shadow-sm h-100" style="border-radius:1rem"><div class="card-body p-4"><h5 class="fw-bold"><i class="fa-solid fa-bullseye text-success me-2"></i>Misi</h5><p class="text-muted mb-0">{{ $misi }}</p></div></div></div></div>
<div class="d-flex justify-content-between align-items-center mb-3"><h4 class="fw-bold mb-0" style="font-family:serif">Informasi & Kegiatan</h4><span class="text-muted small">Dikelola oleh admin</span></div><div class="row g-4">@forelse($news as $item)<div class="col-md-6 col-lg-4"><article class="card border-0 shadow-sm h-100 overflow-hidden" style="border-radius:1rem">@if($item->image_path)<img src="{{ asset('storage/'.$item->image_path) }}" style="height:180px;object-fit:cover" alt="{{ $item->title }}">@endif<div class="card-body p-4"><small class="text-success">{{ $item->type === 'kegiatan' ? 'Kegiatan' : 'Informasi' }} · {{ $item->event_date?->translatedFormat('d F Y') ?? 'Pengumuman' }}</small><h5 class="fw-bold mt-1">{{ $item->title }}</h5><p class="text-muted small mb-0">{{ $item->description }}</p></div></article></div>@empty<div class="col-12"><div class="card border-0 bg-light"><div class="card-body text-muted">Belum ada informasi atau kegiatan yang diterbitkan.</div></div></div>@endforelse</div>
@endsection
