@extends('warga.layout')
@section('title', 'Kas Keluarga | Masjid Jami Cicangkudu')
@section('header', 'Kas Keluarga')
@section('content')
@php($statusLabels = ['pending' => ['Menunggu Verifikasi', 'warning'], 'verified' => ['Sudah Bayar', 'success'], 'rejected' => ['Bukti Ditolak', 'danger'], 'belum_bayar' => ['Belum Bayar', 'secondary']])
<div class="mb-4"><a href="{{ route('dashboard') }}" class="text-decoration-none text-muted small"><i class="fa-solid fa-arrow-left me-1"></i>Kembali ke Dashboard</a><h2 class="fw-bold mt-2 mb-1" style="font-family:serif">Kas Keluarga</h2><p class="text-muted mb-0">Kas berlaku untuk satu KK. Bukti pembayaran akan diperiksa pengurus terlebih dahulu.</p></div>
@if(! $family)<div class="alert alert-warning"><strong>Data KK belum tersedia.</strong> Hubungi pengurus agar akun Anda dihubungkan ke KK.</div>@else
<div class="row g-4 mb-4"><div class="col-lg-7"><div class="card border-0 shadow-sm h-100" style="border-radius:1rem"><div class="card-body p-4"><h5 class="fw-bold">Identitas Kas Keluarga</h5><dl class="row mb-0"><dt class="col-sm-5 text-muted">Nama akun</dt><dd class="col-sm-7">{{ auth()->user()->name }}</dd><dt class="col-sm-5 text-muted">NIK</dt><dd class="col-sm-7">{{ $profile->nik }}</dd><dt class="col-sm-5 text-muted">No. KK</dt><dd class="col-sm-7 fw-semibold">{{ $family->no_kk }}</dd><dt class="col-sm-5 text-muted">Golongan</dt><dd class="col-sm-7">Golongan {{ $family->golongan }}</dd><dt class="col-sm-5 text-muted">Kas wajib</dt><dd class="col-sm-7 fw-semibold text-success">Rp {{ number_format($family->nominal_kas,0,',','.') }} / bulan</dd></dl></div></div></div><div class="col-lg-5"><div class="card border-0 shadow-sm h-100" style="border-radius:1rem"><div class="card-body p-4"><h5 class="fw-bold">Kas {{ \Carbon\Carbon::create(null,$bulan,1)->translatedFormat('F') }} {{ $tahun }}</h5>@php($periodeStatus=$paymentPeriode?->status ?? 'belum_bayar')<p class="mb-3">Status: <span class="badge bg-{{ $statusLabels[$periodeStatus][1] }}">{{ $statusLabels[$periodeStatus][0] }}</span></p>@if($periodeStatus==='verified')<p class="text-muted small">Sudah diverifikasi pengurus{{ $paymentPeriode->payer ? ' · dibayar oleh '.$paymentPeriode->payer->name : '' }}.</p>@elseif($periodeStatus==='pending')<p class="text-muted small">Bukti dari {{ $paymentPeriode->payer?->name ?? 'anggota KK' }} sedang menunggu verifikasi pengurus. Anggota KK lain tidak perlu membayar lagi.</p>@else@if($periodeStatus==='rejected')<div class="alert alert-danger small py-2">Bukti sebelumnya ditolak. Silakan unggah bukti pembayaran yang baru.</div>@endif<form method="POST" enctype="multipart/form-data" action="{{ route('kas.saya.bayar') }}">@csrf<input type="hidden" name="bulan" value="{{ $bulan }}"><input type="hidden" name="tahun" value="{{ $tahun }}"><label class="form-label small fw-semibold">Bukti transfer (JPG, PNG, atau PDF)</label><input type="file" name="proof" accept="image/jpeg,image/png,application/pdf" class="form-control @error('proof') is-invalid @enderror" required>@error('proof')<div class="invalid-feedback">{{ $message }}</div>@enderror<button class="btn btn-success w-100 mt-3">Kirim Bukti Kas Rp {{ number_format($family->nominal_kas,0,',','.') }}</button></form>@endif</div></div></div></div>
<div class="card border-0 shadow-sm" style="border-radius:1rem"><div class="card-body p-4"><h5 class="fw-bold mb-3">Riwayat Kas KK {{ $family->no_kk }}</h5><div class="table-responsive"><table class="table align-middle mb-0"><thead class="table-light"><tr><th>Periode</th><th>Nominal</th><th>Pembayar</th><th>Status</th></tr></thead><tbody>@forelse($payments as $payment)<tr><td>{{ \Carbon\Carbon::create(null,$payment->bulan,1)->translatedFormat('F') }} {{ $payment->tahun }}</td><td>Rp {{ number_format($payment->nominal,0,',','.') }}</td><td>{{ $payment->payer?->name ?? '-' }}</td><td><span class="badge bg-{{ $statusLabels[$payment->status][1] }}">{{ $statusLabels[$payment->status][0] }}</span></td></tr>@empty<tr><td colspan="4" class="text-center text-muted py-4">Belum ada riwayat kas untuk KK ini.</td></tr>@endforelse</tbody></table></div></div></div>
@endif
@endsection
