@extends('admin.layout')
@section('title', 'Verifikasi Pembayaran | Admin Masjid')
@section('header', 'Verifikasi Pembayaran')
@section('content')
<div class="mb-4"><h2 class="fw-bold mb-1" style="font-family:serif">Verifikasi Pembayaran</h2><p class="text-muted mb-0">Periksa bukti donasi dan pembayaran kas KK dalam satu halaman.</p></div>

<div class="card border-0 shadow-sm mb-4" style="border-radius:1rem"><div class="card-body p-4"><h5 class="fw-bold mb-3">Donasi menunggu verifikasi</h5><div class="table-responsive"><table class="table align-middle mb-0"><thead class="table-light"><tr><th>Donatur</th><th>Nominal</th><th>Metode</th><th>Bukti</th><th class="text-center">Aksi</th></tr></thead><tbody>@forelse($pendingDonations as $donation)<tr><td>{{ $donation->user?->name ?? $donation->donor_name ?? 'Hamba Allah' }}</td><td>Rp {{ number_format($donation->amount,0,',','.') }}</td><td class="text-uppercase">{{ $donation->payment_method }}</td><td><a target="_blank" class="btn btn-sm btn-outline-primary" href="{{ asset('storage/'.$donation->proof_path) }}">Lihat bukti</a></td><td class="text-center"><form action="{{ route('admin.donations.verify',$donation) }}" method="POST" class="d-inline">@csrf @method('PUT')<button class="btn btn-sm btn-success" onclick="return confirm('Verifikasi donasi ini?')">Terima</button></form><form action="{{ route('admin.donations.reject',$donation) }}" method="POST" class="d-inline">@csrf @method('PUT')<button class="btn btn-sm btn-outline-danger" onclick="return confirm('Tolak bukti donasi ini?')">Tolak</button></form></td></tr>@empty<tr><td colspan="5" class="text-center text-muted py-3">Tidak ada donasi yang menunggu.</td></tr>@endforelse</tbody></table></div></div></div>

<div class="card border-0 shadow-sm" style="border-radius:1rem"><div class="card-body p-4"><h5 class="fw-bold mb-3">Kas KK menunggu verifikasi</h5><div class="table-responsive"><table class="table align-middle mb-0"><thead class="table-light"><tr><th>No. KK</th><th>Pembayar</th><th>Nominal</th><th>Metode</th><th>Bukti</th><th class="text-center">Aksi</th></tr></thead><tbody>@forelse($pendingKasPayments as $payment)<tr><td>{{ $payment->family->no_kk }}</td><td>{{ $payment->payer?->name ?? '-' }}<small class="d-block text-muted">{{ $payment->payer?->wargaProfile?->nik ?? '-' }}</small></td><td>Rp {{ number_format($payment->nominal,0,',','.') }}</td><td class="text-uppercase">{{ str_replace('_',' ',$payment->payment_method) }}</td><td>@if($payment->proof_path)<a target="_blank" class="btn btn-sm btn-outline-primary" href="{{ asset('storage/'.$payment->proof_path) }}">Lihat bukti</a>@else<span class="text-muted">Tunai</span>@endif</td><td class="text-center"><form action="{{ route('admin.kas-kk.verify',$payment) }}" method="POST" class="d-inline">@csrf @method('PUT')<button class="btn btn-sm btn-success" onclick="return confirm('Verifikasi pembayaran kas ini?')">Terima</button></form><form action="{{ route('admin.kas-kk.reject',$payment) }}" method="POST" class="d-inline">@csrf @method('PUT')<button class="btn btn-sm btn-outline-danger" onclick="return confirm('Tolak pembayaran kas ini?')">Tolak</button></form></td></tr>@empty<tr><td colspan="6" class="text-center text-muted py-3">Tidak ada pembayaran kas yang menunggu.</td></tr>@endforelse</tbody></table></div></div></div>
@endsection
